# Generated by Django 2.0.6 on 2019-05-26 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lrapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='用户注册码')),
                ('code_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lrapp.User', verbose_name='关联的用户')),
            ],
            options={
                'db_table': 'check_user',
            },
        ),
    ]
